import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Nats from "@/components/Nats";
import { NatsProvider } from "@/contexts/NatsContext";
import React from "react";
import Kv from "@/components/Kv";
import Obj from "@/components/Obj";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create NATS App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
              src="/nats.png"
              alt="NATS logo"
              width={360}
              height={96}
              priority
          />
          <>
          <NatsProvider url="wss://demo.nats.io:8443">
            <Nats />
            <Kv />
            <Obj />
          </NatsProvider>
            </>
        </main>
        <footer className={styles.footer}>
        </footer>
      </div>
    </>
  );
}
