import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";

import { useEffect, useState } from "react";
import { wsconnect } from "@nats-io/nats-core";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

function Msgs({ msgs }) {
  const list = msgs.map((d) => (
    <p key={d.id}>
      <strong>{d.id}</strong> <em>{d.msg.subject}</em>: {d.msg.string()}
    </p>
  ));

  return <ul>{list}</ul>;
}

function Nats({ url }) {
  const [nc, setNc] = useState(null);
  const [connected, setConnected] = useState("");
  const [err, setErr] = useState("");
  const [messages, setMessages] = useState([]);

  let i = 1;

  function updateMessages(m) {
    setMessages((messages) => {
      const a = [...messages, m];
      return a.length > 10 ? a.slice(-10) : a;
    });
  }

  function callback(err, msg) {
    if (err) {
      console.log(err);
      setErr(err.message);
    } else {
      const m = {
        id: i++,
        msg: msg,
      };
      updateMessages(m);
    }
  }

  useEffect(() => {
    if (!nc) {
      wsconnect({ servers: url })
        .then((c) => {
          setConnected(`connected to ${c.getServer()}`);
          c.subscribe(">", { callback });
          setNc(c);
        })
        .catch((err) => {
          console.log(err);
          setErr(err.message);
        });
    }
  }, [nc, messages, connected, err]);

  return (
    <>
      <h3>{connected}</h3>
      <Msgs msgs={messages} />
      <p>{err}</p>
    </>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create NATS App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            src="/nats.png"
            alt="NATS logo"
            width={180}
            height={38}
            priority
          />
          <Nats url="wss://demo.nats.io:8443" />
        </main>
        <footer className={styles.footer}>
        </footer>
      </div>
    </>
  );
}
