import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import dynamic from "next/dynamic";
import styles from "@/styles/Home.module.css";

// WebSocket only runs in the browser; skip SSR for the NATS app.
const NatsApp = dynamic(() => import("@/components/NatsApp"), { ssr: false });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create NATS App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            src="/nats.png"
            alt="NATS logo"
            width={360}
            height={96}
            priority
          />
          <NatsApp />
        </main>
        <footer className={styles.footer}></footer>
      </div>
    </>
  );
}
